version: "3.9"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: remedidb
      POSTGRES_USER: remedidbuser
      POSTGRES_PASSWORD: remedipass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./backend:/app
      - media_data:/app/media
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
      - POSTGRES_DB=remedidb
      - POSTGRES_USER=remedidbuser
      - POSTGRES_PASSWORD=remedipass
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - SECRET_KEY=changeme
      - DEBUG=0
      - ALLOWED_HOSTS=*
    depends_on:
      - db
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres_data:
  media_data: