# Generated by Django 5.2.4 on 2025-07-08 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OrgProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "org_type",
                    models.CharField(
                        choices=[
                            ("HOSPITAL", "Hospital"),
                            ("PHARMACY", "Pharmacy"),
                            ("NGO", "NGO"),
                            ("CLINIC", "Clinic"),
                        ],
                        max_length=20,
                    ),
                ),
                ("license_number", models.CharField(max_length=100)),
                ("license_document", models.FileField(upload_to="licenses/")),
                ("address", models.TextField()),
                ("phone", models.CharField(max_length=30)),
                ("is_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
