# Generated by Django 5.2.4 on 2025-07-08 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("approve", "Approve"),
                            ("reject", "Reject"),
                            ("export", "Export"),
                            ("other", "Other"),
                        ],
                        max_length=32,
                    ),
                ),
                ("target_model", models.CharField(max_length=128)),
                ("target_id", models.CharField(blank=True, max_length=128, null=True)),
                ("description", models.TextField(blank=True, default="")),
                ("ip_address", models.CharField(blank=True, default="", max_length=64)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("extra", models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
