# Generated by Django 5.2.4 on 2025-07-08 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="License",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "license_type",
                    models.CharField(
                        choices=[
                            ("pharmacy", "Pharmacy"),
                            ("hospital", "Hospital"),
                            ("ngo", "NGO"),
                            ("clinic", "Clinic"),
                        ],
                        max_length=50,
                    ),
                ),
                ("document", models.FileField(upload_to="licenses/")),
                ("license_number", models.CharField(max_length=128)),
                ("issued_date", models.DateField()),
                ("expiry_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("visibility_public", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
