# Generated by Django 5.2.4 on 2025-07-08 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("licenses", "0001_initial"),
        ("orgs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="license",
            name="org",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="licenses",
                to="orgs.orgprofile",
            ),
        ),
    ]
